-- Community catalog facts checked against Sonic Wiki Zone on 2026-09-12.
-- This migration fills data the current domain can represent without inventing compatibility
-- rules or adding character/machine/part stat columns. See docs/game-data-sources.md.

UPDATE racers SET racing_type = typed.racing_type
FROM (VALUES
    ('Cream & Cheese', 'HANDLING'),
    ('Silver the Hedgehog', 'HANDLING'),
    ('Blaze the Cat', 'SPEED'),
    ('Rouge the Bat', 'HANDLING'),
    ('E-123 Omega', 'POWER'),
    ('Vector the Crocodile', 'POWER'),
    ('Espio the Chameleon', 'SPEED'),
    ('Charmy Bee', 'ACCELERATION'),
    ('Zavok', 'POWER'),
    ('Zazz', 'ACCELERATION'),
    ('Dr. Eggman', 'POWER'),
    ('Metal Sonic', 'SPEED'),
    ('Egg Pawn', 'ACCELERATION'),
    ('Sage', 'ACCELERATION'),
    ('Jet the Hawk', 'SPEED'),
    ('Wave the Swallow', 'ACCELERATION'),
    ('Storm the Albatross', 'POWER'),
    ('Hatsune Miku', 'BOOST'),
    ('Joker', 'HANDLING'),
    ('Ichiban Kasuga', 'POWER'),
    ('NiGHTS', 'SPEED'),
    ('AiAi', 'HANDLING'),
    ('Tangle', 'ACCELERATION'),
    ('Whisper', 'BOOST'),
    ('Red', 'SPEED'),
    ('Goro Majima (Captain Majima)', 'ACCELERATION'),
    ('Arle', 'HANDLING'),
    ('Classic Sonic', 'SPEED'),
    ('Axel', 'ACCELERATION'),
    ('Amigo', 'HANDLING'),
    ('Steve', 'POWER'),
    ('Alex', 'POWER'),
    ('Creeper', 'ACCELERATION'),
    ('SpongeBob SquarePants', 'HANDLING'),
    ('Patrick Star', 'POWER'),
    ('PAC-MAN', 'ACCELERATION'),
    ('Blinky', 'SPEED'),
    ('Mega Man', 'POWER'),
    ('Proto Man', 'SPEED'),
    ('Leonardo', 'SPEED'),
    ('Raphael', 'POWER'),
    ('Donatello', 'HANDLING'),
    ('Michelangelo', 'ACCELERATION'),
    ('Tails Nine', 'ACCELERATION'),
    ('Knuckles the Dread', 'POWER'),
    ('Rusty Rose', 'HANDLING'),
    ('Werehog', 'POWER')
) AS typed(name, racing_type)
WHERE racers.name = typed.name;

-- Released stock machines missing from the previous evidence-limited catalog.
-- Image paths stay NULL until an isolated local asset is deliberately added.
INSERT INTO machines (id, name, racing_type) VALUES
(md5('ringlab:wiki-machine:Mirage Blade')::uuid, 'Mirage Blade', 'SPEED'),
(md5('ringlab:wiki-machine:Super Shining')::uuid, 'Super Shining', 'SPEED'),
(md5('ringlab:wiki-machine:Royal Chariot')::uuid, 'Royal Chariot', 'SPEED'),
(md5('ringlab:wiki-machine:Stealth Chaser')::uuid, 'Stealth Chaser', 'SPEED'),
(md5('ringlab:wiki-machine:Retro Future')::uuid, 'Retro Future', 'SPEED'),
(md5('ringlab:wiki-machine:Wild GT')::uuid, 'Wild GT', 'SPEED'),
(md5('ringlab:wiki-machine:Buster M')::uuid, 'Buster M', 'SPEED'),
(md5('ringlab:wiki-machine:Hyper Scorpion')::uuid, 'Hyper Scorpion', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Cyber Spear')::uuid, 'Cyber Spear', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Pawn Calibur')::uuid, 'Pawn Calibur', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Long Stinger')::uuid, 'Long Stinger', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Radical Fours')::uuid, 'Radical Fours', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Racing Buggy')::uuid, 'Racing Buggy', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Giganto Liner')::uuid, 'Giganto Liner', 'ACCELERATION'),
(md5('ringlab:wiki-machine:Lip Spyder')::uuid, 'Lip Spyder', 'HANDLING'),
(md5('ringlab:wiki-machine:Victoria Carriage')::uuid, 'Victoria Carriage', 'HANDLING'),
(md5('ringlab:wiki-machine:Moto Beetle')::uuid, 'Moto Beetle', 'HANDLING'),
(md5('ringlab:wiki-machine:Ancient Throne')::uuid, 'Ancient Throne', 'HANDLING'),
(md5('ringlab:wiki-machine:Little Lady')::uuid, 'Little Lady', 'HANDLING'),
(md5('ringlab:wiki-machine:Hot Hatch')::uuid, 'Hot Hatch', 'HANDLING'),
(md5('ringlab:wiki-machine:Fossil Rock')::uuid, 'Fossil Rock', 'HANDLING'),
(md5('ringlab:wiki-machine:Knight Tank')::uuid, 'Knight Tank', 'POWER'),
(md5('ringlab:wiki-machine:Fang Loader')::uuid, 'Fang Loader', 'POWER'),
(md5('ringlab:wiki-machine:Beat Gator')::uuid, 'Beat Gator', 'POWER'),
(md5('ringlab:wiki-machine:Frog Cruiser')::uuid, 'Frog Cruiser', 'POWER'),
(md5('ringlab:wiki-machine:Cross Dozer')::uuid, 'Cross Dozer', 'POWER'),
(md5('ringlab:wiki-machine:Trail Runner')::uuid, 'Trail Runner', 'POWER'),
(md5('ringlab:wiki-machine:Egg Drillster Mk.II')::uuid, 'Egg Drillster Mk.II', 'POWER'),
(md5('ringlab:wiki-machine:Beast Spike')::uuid, 'Beast Spike', 'POWER'),
(md5('ringlab:wiki-machine:Sakura Board')::uuid, 'Sakura Board', 'BOOST'),
(md5('ringlab:wiki-machine:Triple Fan')::uuid, 'Triple Fan', 'BOOST'),
(md5('ringlab:wiki-machine:Pop Float')::uuid, 'Pop Float', 'BOOST'),
(md5('ringlab:wiki-machine:TYPE-W Windy')::uuid, 'TYPE-W Windy', 'BOOST'),
(md5('ringlab:wiki-machine:Wispon Booster')::uuid, 'Wispon Booster', 'BOOST'),
(md5('ringlab:wiki-machine:Quad Copter')::uuid, 'Quad Copter', 'BOOST'),
(md5('ringlab:wiki-machine:Jaws Rocket')::uuid, 'Jaws Rocket', 'BOOST');

UPDATE machines SET racing_type = typed.racing_type
FROM (VALUES
    ('Diva Macchina', 'BOOST'), ('Arsene Wing', 'SPEED'),
    ('Dragon Brave', 'POWER'), ('Dream Sleeper', 'BOOST'),
    ('Banana Cruiser', 'SPEED'), ('Super Roaster', 'ACCELERATION'),
    ('Goromaru', 'POWER'), ('Twinkle Bayoen', 'ACCELERATION'),
    ('Mach Cyclone', 'SPEED'), ('Devolada Yellow Jack', 'SPEED'),
    ('Minecart', 'HANDLING'), ('Patty Wagon', 'HANDLING'),
    ('PAC-MAN Mobile', 'HANDLING'), ('Rush Roadstar', 'ACCELERATION'),
    ('Pizzafire Van', 'POWER'), ('Blue Star', 'BOOST')
) AS typed(name, racing_type)
WHERE machines.name = typed.name;

-- Every stock machine contributes one front, rear and tire entry in RingLab's current model.
INSERT INTO machine_parts (id, source_machine_id, part_type)
SELECT md5('ringlab:catalog-part:' || m.id::text || ':' || p.part_type)::uuid, m.id, p.part_type
FROM machines m CROSS JOIN (VALUES ('FRONT'), ('REAR'), ('TIRE')) AS p(part_type)
WHERE NOT EXISTS (
    SELECT 1 FROM machine_parts existing
    WHERE existing.source_machine_id = m.id AND existing.part_type = p.part_type
);

-- Current community catalog descriptions and plate costs for already-present gadgets.
UPDATE gadgets SET description = facts.description, slot_cost = facts.slot_cost
FROM (VALUES
    ('Champion Bounty', 'Get Rings while in 1st through 3rd place.', 3),
    ('Route Planner Bounty', 'When choosing a Travel Ring, get 100 Rings and increase the maximum Ring limit.', 1),
    ('Starting Boost Bounty', 'Get Rings with a successful Starting Boost.', 1),
    ('Ring Doubler', 'Double the number of Rings gained. Not counted for Team Matches.', 3),
    ('Less is More', 'Increase the Machine''s top speed when holding fewer Rings.', 3),
    ('Ring Engine', 'While holding at least 1 Ring, gain +12 to all stats but slowly lose Rings over time.', 1),
    ('Hyper Ring Engine', 'While holding at least 1 Ring, increase all stats based on Rings held but slowly lose Rings over time.', 2),
    ('130 Ring Limit', 'Hold up to 130 Rings.', 1),
    ('Mini Ring Thief', 'Steal a small amount of Rings when colliding with other Machines.', 1),
    ('Ring Thief', 'Steal Rings when colliding with other Machines.', 2),
    ('Extended Slipstream', 'Make slipstreams occur more often.', 1),
    ('Ultimate Air Trick', 'Do more than 3 Air Tricks to become invincible for a short time.', 2),
    ('Perfect Landing', 'Press accelerate as soon as you land to get a speed boost.', 1),
    ('Collision Boost', 'Collide with a Machine to Boost.', 2),
    ('Spin Drift', 'While drifting, spin at high speed and knock away other Machines.', 2),
    ('Ultimate Charge', 'Add a fourth Drift Charge level and become invincible during its boost.', 2),
    ('Perfect Charge Boost', 'Release the drift as soon as a Charge Level fills to Boost faster.', 2),
    ('Friction Drift', 'Slow down while drifting in land form, but charge the Drift Gauge much faster.', 2),
    ('Ring Evolution', 'Get 10 Rings to change all stats by +1.', 1),
    ('Collision Evolution', 'Bump into other Machines to change all stats by +1.', 1),
    ('Damage Evolution', 'Taking damage changes all stats by +7.', 1),
    ('Item Hit Evolution', 'Land a hit with an item to change all stats by +7.', 1),
    ('Quick Starter', 'Gain +20 to all stats during Lap 1.', 1),
    ('Super Quick Starter', 'Gain +60 to all stats during Lap 1.', 2),
    ('Slow Starter', 'Gain +20 to all stats during Lap 3.', 2),
    ('Super Slow Starter', 'Gain +60 to all stats during Lap 3.', 3),
    ('Substitute Item', 'Taking a homing-item hit loses held items but grants invincibility.', 1),
    ('Ring Mercy', 'Get Rings after taking damage.', 1),
    ('Damage Mercy', 'Become temporarily invincible after taking damage.', 2),
    ('Item Mercy', 'Get an item after taking damage.', 2),
    ('Invincible Start', 'Become invincible for a short time when the race starts.', 2),
    ('Strong Finish', 'Become temporarily invincible on Lap 3.', 2),
    ('Invincible Finish', 'Become invincible when close to the finish line.', 3),
    ('Item Keeper', 'Prevent items from being dropped.', 2),
    ('Quick Recovery', 'Recover from attacks faster.', 3),
    ('Crash Pads', 'Halve the number of Rings lost when taking damage.', 1),
    ('Summon Item Box', 'Spend 40 Rings with the Gadget Button to get an item.', 2),
    ('Lucky Pair', 'Occasionally get double items.', 2),
    ('Double Down', 'Debuff all stats, but always get double items.', 3),
    ('Inventory Swap', 'Use the Gadget Button to change item order.', 3),
    ('Item Stock Plus', 'Hold up to 3 items instead of 2.', 2),
    ('Hazard Item Chance UP', 'Hazard items appear more often.', 1),
    ('Attack Item Chance UP', 'Attack items appear more often.', 1),
    ('Defense Item Chance UP', 'Defense items appear more often.', 2),
    ('Boost Item Chance UP', 'Boost items appear more often.', 3),
    ('Wisp Chance UP', 'Wisp items appear more often.', 1),
    ('Go Go Omochao', 'Omochao distributes Rings for longer and appears more often.', 2),
    ('Warp Ring Specialist', 'Start with a Warp Ring; Warp Rings can also appear in Item Boxes.', 2),
    ('Giant Rocket Punch', 'Rocket Punch becomes bigger and appears more often.', 1),
    ('Drift Charge Kit', 'Fill the Drift Gauge faster and slightly improve Handling.', 3),
    ('Speed Machine Kit', 'Get more Rings and accelerate with them; Speed Machines receive stat adjustments.', 3),
    ('Acceleration Machine Kit', 'Reduce the impact of damage; Acceleration Machines receive stat adjustments.', 3),
    ('Handling Machine Kit', 'Become invincible with Charge Level 4 Boosts; Handling Machines receive stat adjustments.', 3),
    ('Power Machine Kit', 'Boost when colliding with other Machines; Power Machines receive stat adjustments.', 3),
    ('Speed Character Kit', 'Become invincible at the start and get Rings from a successful Starting Boost; Speed characters receive stat adjustments.', 3),
    ('Acceleration Character Kit', 'Catch up with other racers and get Rings; Acceleration characters receive stat adjustments.', 3),
    ('Handling Character Kit', 'Collide with racers and steal Rings; Handling characters receive stat adjustments.', 3),
    ('Power Character Kit', 'Catch up with racers and Boost on collision; Power characters receive stat adjustments.', 3),
    ('Boost Character Kit', 'Accelerate with Air Tricks; Boost characters receive stat adjustments.', 3),
    ('Spin Dash Kit', 'Change drift charging to repeated acceleration presses; charges build slower but last longer.', 3),
    ('Panel Combo Kit', 'Use Dash Panels to get Rings; consecutive panels give more Rings and increase Power and Handling.', 3),
    ('Drift Spinner Kit', 'Fill Level 1 Drift Charge slightly faster and knock away Machines while drifting.', 3),
    ('Item Buster Kit', 'Make Attack items more common and get Rings for attacking racers.', 3),
    ('Wisp Hoarder Kit', 'Use many Wisp items and gain items when completing laps.', 3),
    ('All-Rounder Kit', 'Reduce deceleration-area and slippery-road effects and greatly improve water and flight stats.', 3),
    ('Sea Dog Kit', 'Improve water-form performance and perform Air Tricks much faster.', 3),
    ('Ace Pilot Kit', 'Improve flight-form performance and gain Rings from Dash Panels and Gates.', 3),
    ('Comeback Kit', 'Raise the Ring limit to 110 and gain 2 items on Lap 3.', 3)
) AS facts(name, description, slot_cost)
WHERE gadgets.name = facts.name;
